name: CICD

# Controls when the action will run. 
on:
  # Triggers the workflow on pull request events for dev and main
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Run Test & Deploy'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Based on https://github.com/valora-inc/wallet/blob/main/.github/workflows/check.yml
  test:
    name: Test
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          check-latest: true
      - name: Install dependencies
        run: npm install
      - name: Run Jest Tests
        run: npm run test
  deploy: 
    name: Deploy to GH Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          check-latest: true
      - name: Install dependencies
        run: npm install
      - name: Run Build
        run: npm run build --if-present
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_Token }}